[project]
name = "impulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "deskew>=1.5.3",
    "fabric>=3.2.2",
    "fireworks>=2.0.5",
    "loguru>=0.7.3",
    "lxml>=6.0.2",
    "matplotlib>=3.10.6",
    "mplcursors>=0.7",
    "pandas>=2.3.3",
    "pillow>=10.4.0",
    "plotly>=6.3.1",
    "pymongo>=4.15.2",
    "pypdf2>=3.0.1",
    "python-doctr>=1.0.0",
    "sentence-transformers>=5.1.1",
    "smbprotocol[kerberos]>=1.15.0",
    "transformers>=4.57.0",
    "woolworm>=0.0.9",
]
